name: Hallo Wereld ci/cd Texel TechLab pipeline

on: push

jobs:
  hallo-wereld:
    runs-on: ubuntu-latest
    steps:
      - name: Zeg Hallo
        run: echo "Hallo, Dineke!"
  hallo-wereld2:
    runs-on: ubuntu-latest
    steps:
      - name: Zeg Hallo2
        run: echo "Hallo, Ruben!"
